In [1]:
import pandas as pd
df = pd.read_csv("./u.data",sep="\t")
df.shape
df.columns = ["UserId","MovieId","Rating","TimeStamp"]

In [2]:
ratings = df
ratings.shape

(99999, 4)

In [3]:
movies = pd.read_csv("./u.item",sep="|",encoding="ISO-8859-1")
movies.shape

(1681, 24)

In [4]:
movies.columns = ["MovieId","MovieTitle","ReleaseDate","VideoReleaseDate","IMDbURL","Unknown","Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy","FilmNoir","Horror","Musical","Mystery","Romance","SciFi","Thriller","War","Western"]

In [5]:
movies1 = movies.drop(["MovieTitle","ReleaseDate","VideoReleaseDate","IMDbURL"],axis=1)
movies1

,MovieId,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western
0,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,4,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
4,6,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
5,7,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
6,8,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0
7,9,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
8,10,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
9,11,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
10,12,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
11,13,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
12,14,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
13,15,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
14,16,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
15,17,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0
16,18,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
17,19,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
18,20,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
19,21,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0
20,22,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
21,23,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
22,24,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
23,25,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
24,26,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,27,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,28,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
27,29,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
28,30,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
29,31,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,1653,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1652,1654,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1653,1655,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1654,1656,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1655,1657,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1656,1658,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1657,1659,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1658,1660,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1659,1661,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1660,1662,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1661,1663,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1662,1664,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1663,1665,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1664,1666,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1665,1667,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1666,1668,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1667,1669,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0
1668,1670,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1669,1671,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1670,1672,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1671,1673,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1672,1674,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1673,1675,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1674,1676,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1675,1677,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1676,1678,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1677,1679,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1678,1680,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1679,1681,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1680,1682,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [6]:
ratings_ctx = ratings.merge(movies1,on="MovieId")
ratings_ctx.shape
ratings_ctx["TimeStamp"]

0        891717742
1        891560253
2        888065432
3        880928519
4        879371909
5        888180227
6        891409070
7        892668197
8        891033606
9        879465986
10       878961511
11       879138235
12       881547719
13       886307860
14       892239796
15       880680541
16       891374528
17       888103530
18       881514811
19       879799301
20       891037111
21       879949347
22       891544177
23       883108157
24       886398509
25       879544201
26       879161553
27       891037385
28       877584085
29       880353526
           ...
99517    885546288
99518    881372849
99519    885546529
99520    891695570
99521    887523224
99522    892335187
99523    888980193
99524    892871732
99525    891500194
99526    878962816
99527    891497793
99528    878962169
99529    878962240
99530    887473570
99531    887160722
99532    887488947
99533    891500110
99534    884222085
99535    892335460
99536    893115576
99537    893212484
99538    884795447
99539    892871225
99540    888733313
99541    880845755
99542    891211682
99543    888474646
99544    888984255
99545    887428735
99546    887427810
Name: TimeStamp, Length: 99547, dtype: int64

In [7]:
ratings_ctx.columns

Index(['UserId', 'MovieId', 'Rating', 'TimeStamp', 'Unknown', 'Action',
       'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Fantasy', 'FilmNoir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'SciFi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [8]:
from datetime import datetime
def time_hour(t):
    d = datetime.utcfromtimestamp(t)#估计我的时区和作者
    return d.timetuple().tm_hour
time_hour(887731052)
ratings_ctx["hours"] =  ratings_ctx["TimeStamp"].apply(time_hour)
ratings_ctx.head()

,UserId,MovieId,Rating,TimeStamp,Unknown,Action,Adventure,Animation,Children,Comedy,...,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western,hours
0,186,302,3,891717742,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,19
1,191,302,4,891560253,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,23
2,49,302,4,888065432,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,12
3,54,302,4,880928519,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,22
4,62,302,3,879371909,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,21

In [122]:
#针对某个用户的数据按照某个上下文属性使用了分组，然后归一化形成新表之后，要加上备份的index，这样就有一个上下文的维度表。这是关于小时维度的
target_uer = ratings_ctx[ ratings_ctx["UserId"] == 222]
target_uer_agg = target_uer.drop(["UserId","TimeStamp","Rating","Unknown","MovieId"],axis=1).set_index('hours').groupby('hours').sum()
target_uer_agg["context"] = target_uer_agg.index
p =  target_uer_agg.index
target_uer_agg = (target_uer_agg - target_uer_agg.min()) / (target_uer_agg.max() - target_uer_agg.min())
target_uer_agg["context"] = p
target_uer_agg

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western,context
hours,,,,,,,,,,,,,,,,,,,
3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.000000,1.00,1.000000,1.000000,1.00000,1.000000,1.00,3
4,0.675676,0.571429,0.000000,0.181818,0.387755,0.214286,0.0,0.403846,0.333333,0.333333,0.7,0.250000,1.00,0.250000,0.666667,0.43750,0.307692,0.25,4
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0.000000,0.00000,0.076923,0.00,7
8,0.000000,0.000000,0.000000,0.000000,0.102041,0.071429,0.0,0.076923,0.000000,0.000000,0.2,0.000000,0.00,0.035714,0.000000,0.09375,0.000000,0.00,8
10,0.324324,0.238095,0.272727,0.227273,0.244898,0.214286,0.0,0.230769,0.000000,0.000000,0.4,0.250000,0.00,0.214286,0.095238,0.15625,0.230769,0.50,10
11,0.216216,0.238095,0.090909,0.045455,0.346939,0.142857,0.0,0.153846,0.000000,0.000000,0.4,0.000000,0.25,0.000000,0.190476,0.12500,0.153846,0.25,11
23,0.702703,0.571429,0.272727,0.136364,0.285714,0.428571,0.0,0.461538,0.666667,0.333333,0.0,0.166667,1.00,0.428571,0.523810,0.62500,0.307692,0.00,23

In [10]:
ratings_no_time = df.drop(["TimeStamp"],axis =1)

In [11]:
ratings_no_time.head()

   UserId  MovieId  Rating
0     186      302       3
1      22      377       1
2     244       51       2
3     166      346       1
4     298      474       4

In [12]:
movies1.shape
a = {'uid': [1, 2,3,4,1], 'mid': [3, 4,4,3,4]}
b = {'c1': [1, 0], 'mid': [3, 4], "c2":[0,1]}
left = pd.DataFrame(data=a) 
right = pd.DataFrame(data=b) 
print(left.merge(right,on="mid"))
print(left.merge(right,on="mid",how="outer"))

   mid  uid  c1  c2
0    3    1   1   0
1    3    4   1   0
2    4    2   0   1
3    4    3   0   1
4    4    1   0   1
   mid  uid  c1  c2
0    3    1   1   0
1    3    4   1   0
2    4    2   0   1
3    4    3   0   1
4    4    1   0   1

In [13]:
import numpy as np
ratings_merge = ratings_no_time.merge(movies1,on="MovieId")
ratings_merge.shape

(99547, 22)

In [14]:
ratings_merge

,UserId,MovieId,Rating,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western
0,186,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
1,191,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,49,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
3,54,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
4,62,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
5,206,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
6,197,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
7,214,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
8,190,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
9,303,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
10,181,302,2,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
11,154,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
12,31,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
13,305,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
14,178,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
15,102,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
16,100,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
17,144,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
18,13,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
19,315,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
20,88,302,3,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
21,282,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
22,334,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
23,208,302,1,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
24,112,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
25,277,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
26,145,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
27,392,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
28,276,302,5,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
29,360,302,4,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99517,405,1564,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99518,456,1604,4,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,1,0,0
99519,405,1574,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
99520,883,1448,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99521,655,1448,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99522,234,1448,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99523,787,1671,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99524,587,1625,4,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
99525,782,1665,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99526,181,1325,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99527,782,1670,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
99528,181,1341,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99529,181,1352,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99530,655,1636,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99531,896,1681,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
99532,655,1638,3,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
99533,782,1667,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99534,851,1675,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99535,234,1460,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
99536,532,1594,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99537,416,1594,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99538,648,1626,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
99539,655,1645,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99540,747,1659,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
99541,916,1682,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99542,840,1674,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99543,655,1640,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99544,655,1637,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99545,655,1630,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99546,655,1641,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
def handlef(x):
    if x > 3:
        return 1
    else:
        return 0
ratings_merge["nrat"] = ratings_merge["Rating"].apply(handlef)
ratings_merge.head()

,UserId,MovieId,Rating,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western,nrat
0,186,302,3,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0
1,191,302,4,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,1
2,49,302,4,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,1
3,54,302,4,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,1
4,62,302,3,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0

In [72]:
ratings_drop = ratings_merge.drop(["Rating","Unknown"],axis=1)
ratings_drop.shape

(99547, 21)

In [123]:
ratings_scale =  ratings_drop.drop(["UserId","MovieId","nrat"],axis=1)
ratings_scale.head()

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western
0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
2,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
3,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
4,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0

In [124]:
ratings_scale = (ratings_scale - ratings_scale.mean()) / (ratings_scale.max() - ratings_scale.min())
ratings_scale["UserId"] = ratings_drop["UserId"]
ratings_scale["MovieId"] = ratings_drop["MovieId"]
ratings_scale["nrat"] = ratings_drop["nrat"]

ratings_scale.head()
# ratings_scale.shape

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,FilmNoir,...,Musical,Mystery,Romance,SciFi,Thriller,War,Western,UserId,MovieId,nrat
0,-0.257054,-0.138156,-0.031673,-0.067606,-0.295127,0.919083,-0.007614,-0.400765,-0.013582,0.982591,...,-0.049765,0.947311,-0.195496,-0.127879,0.780285,-0.094408,-0.018624,186,302,0
1,-0.257054,-0.138156,-0.031673,-0.067606,-0.295127,0.919083,-0.007614,-0.400765,-0.013582,0.982591,...,-0.049765,0.947311,-0.195496,-0.127879,0.780285,-0.094408,-0.018624,191,302,1
2,-0.257054,-0.138156,-0.031673,-0.067606,-0.295127,0.919083,-0.007614,-0.400765,-0.013582,0.982591,...,-0.049765,0.947311,-0.195496,-0.127879,0.780285,-0.094408,-0.018624,49,302,1
3,-0.257054,-0.138156,-0.031673,-0.067606,-0.295127,0.919083,-0.007614,-0.400765,-0.013582,0.982591,...,-0.049765,0.947311,-0.195496,-0.127879,0.780285,-0.094408,-0.018624,54,302,1
4,-0.257054,-0.138156,-0.031673,-0.067606,-0.295127,0.919083,-0.007614,-0.400765,-0.013582,0.982591,...,-0.049765,0.947311,-0.195496,-0.127879,0.780285,-0.094408,-0.018624,62,302,0

In [125]:
from sklearn.ensemble import RandomForestClassifier

In [126]:
from sklearn.cross_validation import train_test_split
ratings_train , ratings_test = train_test_split(ratings_scale.values, test_size = 0.2 , random_state = 42)
print(ratings_train.shape , ratings_test.shape)

(79637, 21) (19910, 21)

In [127]:
clf = RandomForestClassifier(max_depth=10, random_state=0 ,n_estimators=100)
x = ratings_train[:, 0:18 ]
y = ratings_train[:, 20:21]
print(x.shape,y.shape)
clf.fit(x, y.ravel())

(79637, 18) (79637, 1)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [128]:
r = clf.predict(ratings_test[:,0:18])
x_test = ratings_test[:, 0:18 ]
y_test = ratings_test[:, 20:21]
print(clf.score(x_test,y_test))

0.597137117027

In [129]:
print(clf.feature_importances_)

[ 0.06670701  0.0692734   0.01762265  0.03909809  0.08545322  0.0419221
  0.00446223  0.19462065  0.01983166  0.04660659  0.04649864  0.04488091
  0.02683036  0.06917076  0.04944117  0.06465567  0.10215635  0.01076857]

In [130]:
total_movieIds = movies1["MovieId"].unique()
total_movieIds

array([   2,    3,    4, ..., 1680, 1681, 1682])

In [131]:
def nonratedmoviedf(userid):
  ratedmovies =  ratings[ratings["UserId"] == userid]["MovieId"]
  d = [mid  for mid in total_movieIds if mid not  in ratedmovies.values] 
  return pd.DataFrame(data={"UserId":[943 for x in range(len(d))] ,"MovieId":d,  "Rating":0 })
    
ndf = nonratedmoviedf(943)

In [90]:
nonratedUserPro = ndf.merge(movies1,on="MovieId")
nonratedUserPro.head()

,MovieId,Rating,UserId,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,FilmNoir,Horror,Musical,Mystery,Romance,SciFi,Thriller,War,Western
0,3,0,943,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,4,0,943,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,5,0,943,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,6,0,943,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,7,0,943,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [143]:
r = clf.predict(nonratedUserPro.values[:,4:22])
nonratedUserPro["Rating"] = r
recommand = nonratedUserPro[nonratedUserPro["Rating"] == 1 ][["MovieId"]]

In [177]:
# r2 = clf.predict(target_uer_agg.values[:,1:19])
pdf = recommand.merge(movies1,on="MovieId")
UCP_pref_content = pdf.drop(["MovieId","Unknown"],axis=1)
print(UCP_pref_content.shape)
print(target_uer_agg.values[4,0:18].shape)#这样得到的是18:1
r = np.dot(UCP_pref_content.values,target_uer_agg.values[4:5,0:18].reshape(18,1))
pdf["SimVal"] = r
view_pef = pdf[["MovieId","SimVal"]].sort_values(by=["SimVal"],ascending=False)
view_pef.head()

(986, 18)
(18,)

     MovieId    SimVal
525      993  1.232993
243      510  1.055094
606     1138  1.014277
233      498  1.007475
311      631  1.000149